import "./globals.css";
import { Metadata } from "next";
import {
  Inter,
  DM_Serif_Display as DMsd,
  Jost,
  Oswald,
  Lexend,
} from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const dmsd = DMsd({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-dmsd",
});
const jost = Jost({ subsets: ["latin"], variable: "--font-jost" });
const oswald = Oswald({ subsets: ["latin"], variable: "--font-oswald" });
const lexend = Lexend({ subsets: ["latin"], variable: "--font-lexend" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${dmsd.variable} 
          ${jost.variable} 
          ${oswald.variable} 
          ${lexend.variable} 
          font-sans
        `}
      >
        {children}
      </body>
    </html>
  );
}
