import './globals.css';
import { Metadata } from 'next';
import {
  DM_Serif_Display as DMsd,
  Jost,
  Oswald,
  Lexend,
  Quattrocento
} from 'next/font/google';

const dmsd = DMsd({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-dmsd'
});
const jost = Jost({ subsets: ['latin'], variable: '--font-jost' });
const oswald = Oswald({ subsets: ['latin'], variable: '--font-oswald' });
const lexend = Lexend({ subsets: ['latin'], variable: '--font-lexend' });
const quattrocento = Quattrocento({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-quattrocento'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${dmsd.variable} 
          ${jost.variable} 
          ${oswald.variable} 
          ${lexend.variable} 
          ${quattrocento.variable} 
          font-sans
        `}
      >
        {children}
      </body>
    </html>
  );
}
